// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
)

type Movie struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Overview    string `json:"overview"`
	ReleaseDate string `json:"release_date"`
	PosterUrl   string `json:"poster_url"`
}

type Rating struct {
	ID      int64         `json:"id"`
	Score   int32         `json:"score"`
	MovieID sql.NullInt32 `json:"movie_id"`
	UserID  sql.NullInt32 `json:"user_id"`
}

type User struct {
	ID       int64       `json:"id"`
	Username string      `json:"username"`
	Password interface{} `json:"password"`
	Email    string      `json:"email"`
}
