// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: ratings.sql

package db

import (
	"context"
	"database/sql"
)

const createRating = `-- name: CreateRating :one
INSERT INTO ratings (
  score,
  movie_id,
  user_id
) VALUES (
  $1, $2, $3
) RETURNING id, score, movie_id, user_id
`

type CreateRatingParams struct {
	Score   int32         `json:"score"`
	MovieID sql.NullInt32 `json:"movie_id"`
	UserID  sql.NullInt32 `json:"user_id"`
}

func (q *Queries) CreateRating(ctx context.Context, arg CreateRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, createRating, arg.Score, arg.MovieID, arg.UserID)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.Score,
		&i.MovieID,
		&i.UserID,
	)
	return i, err
}

const deleteRating = `-- name: DeleteRating :exec
DELETE FROM ratings
WHERE id = $1
`

func (q *Queries) DeleteRating(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRating, id)
	return err
}

const getMovieRatings = `-- name: GetMovieRatings :many
SELECT id, score, movie_id, user_id FROM ratings
WHERE movie_id = $1
`

func (q *Queries) GetMovieRatings(ctx context.Context, movieID sql.NullInt32) ([]Rating, error) {
	rows, err := q.db.QueryContext(ctx, getMovieRatings, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rating
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.ID,
			&i.Score,
			&i.MovieID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRating = `-- name: GetRating :one
SELECT id, score, movie_id, user_id FROM ratings
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRating(ctx context.Context, id int64) (Rating, error) {
	row := q.db.QueryRowContext(ctx, getRating, id)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.Score,
		&i.MovieID,
		&i.UserID,
	)
	return i, err
}

const getUserRatings = `-- name: GetUserRatings :many
SELECT id, score, movie_id, user_id FROM ratings
WHERE user_id = $1
`

func (q *Queries) GetUserRatings(ctx context.Context, userID sql.NullInt32) ([]Rating, error) {
	rows, err := q.db.QueryContext(ctx, getUserRatings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rating
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.ID,
			&i.Score,
			&i.MovieID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRating = `-- name: UpdateRating :one
UPDATE ratings
SET score = $1
WHERE id = $2
RETURNING id, score, movie_id, user_id
`

type UpdateRatingParams struct {
	Score int32 `json:"score"`
	ID    int64 `json:"id"`
}

func (q *Queries) UpdateRating(ctx context.Context, arg UpdateRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, updateRating, arg.Score, arg.ID)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.Score,
		&i.MovieID,
		&i.UserID,
	)
	return i, err
}
